### ISSUE TITLE
(Battery Widget) Unexpected symbol near { in rc.lua

### ISSUE THREAD

**Issue by ranguli** [streetturtle/awesome-wm-widgets#10]
Can we get the rc.lua examples to be copy-pastable?  Disclaimer I have no clue about Lua syntax, so I (assuming the example snippet in battery-widget/README wasn't directly copy/pastable) have been trying to get this to work, and can't resolve the syntax. If you were curious, here's what I have.

```
require("battery")

s.mytasklist,
	{ -- This line give mes an 'unexpected symbol near { in rc.lua'
    	layout = wibox.layout.fixed.horizontal,
		battery_widget,
}
```

But it would be great if non-Lua inclined users could get it up and running faster. I should also clarify I'm on awm 3.5.6, so I'm going to try using the _actual_ compatible version - but it looks like a Lua syntax error not an awm version-related issue.

**Comment by streetturtle** [comment]
I've updated widgets recently to work with Awesome 4 - unfortunately it's not backward compatible with previous version of Awesome. 
You can try this repo: https://github.com/streetturtle/AwesomeWM3#battery-widget but it's not so nice as for v.4 :) And In version 3 widgets are added following way: 

```lua
local right_layout = wibox.layout.fixed.horizontal()
right_layout:add(wibox.widget.systray())
right_layout:add(separator)
right_layout:add(lunchMenuWidget)
right_layout:add(separator)
right_layout:add(mouse_battery_icon)
```

Please let me know if something is unclear.
 I'll update the docs ot make it more clear.

Thanks!
