### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by ReporterNV** [streetturtle/awesome-wm-widgets#100]
Hi. 
Found a small typo in README.md for "Email widget".
In this line:

 _in email.lua **cahnge** path to python scripts_

Thank for your work.

**Comment by streetturtle** [comment]
Thanks! :+1: 
closed by cc2384b926c09bb791105f9804c6b7fbc3b47e7a

**Comment by streetturtle** [comment]
closed by cc2384b
