### ISSUE TITLE
crash after reinstall

### ISSUE THREAD

**Issue by muellert** [streetturtle/awesome-wm-widgets#101]
I have a pretty standard rc.lua, which does not have much  more than the one that came with my system (Debian Buster), but recently, I get tracebacks on these widgets. I used to use the cpu, ram and batteryarc widgets, now I am using none. I have just tried to update my widgets, and my system is otherwise current (ie, 10.2).
![image](https://user-images.githubusercontent.com/1183079/69485716-2ed82d00-0e3b-11ea-84ae-772668a4910b.png)
![image](https://user-images.githubusercontent.com/1183079/69485739-7bbc0380-0e3b-11ea-81c1-e0a7f10758ad.png)

After requiring the "debian.menu", I have this in my rc.lua:

battery_widget = require("awesome-wm-widgets.batteryarc-widget.batteryarc")
cpu_widget = require("awesome-wm-widgets.cpu-widget.cpu-widget")
ram_widget = require("awesome-wm-widgets.ram-widget.ram-widget")

Then, the difference between a working and a broken rc.lua is removing the comment signs from any of the cpu_widget, ram_widget and battery_widget in the following code:

      s.mywibox:setup {
         layout = wibox.layout.align.horizontal,
         { -- Left widgets
            layout = wibox.layout.fixed.horizontal,
            mylauncher,
            s.mytaglist,
            s.mypromptbox,
         },
         s.mytasklist, -- Middle widget
         { -- Right widgets
            layout = wibox.layout.fixed.horizontal,
            mykeyboardlayout,
            wibox.widget.systray(),
            -- cpu_widget,
            -- ram_widget,
            -- battery_widget,
            mytextclock,
            s.mylayoutbox,
         },
      }

What gives?

**Comment by streetturtle** [comment]
Oops, my bad. I think it's because I introduced a breaking change recently. Now widget is a function, not an object. So you just need to add parentheses, like `cpu_widget()`. This was done in order to customize widget directly in rc.lua (for example for cpu widget you can set step width, or step spacing). Please refer to the widgets' readme files for more details.

**Comment by streetturtle** [comment]
So it seems the issue could be closed.
