### ISSUE TITLE
battery_widget not working

### ISSUE THREAD

**Issue by bochku** [streetturtle/awesome-wm-widgets#102]
Hi, I have a pretty vanilla rc.lua, and I followed the given instructions, like adding
`battery_widget = require ( "awesome-wm-widgets.battery-widget.battery" )` and added `battery_widget` before `mytextclock` on the wibox. However nothing seems to be showing on the wibar.
Here's my rc.lua: https://pastebin.com/raw/bde4R7T6

**Comment by streetturtle** [comment]
Sounds like there is no icon under `/usr/share/icons/Arc/status/symbolic/`. Can you check if it's there please.

**Comment by mumuluxi** [comment]
I have the same problem and saw that in contrast to the other widgets of this repro, this one has no icon path that can be changed. Did I misunderstand something or can you maybe just change it?

**Comment by streetturtle** [comment]
Yep, you're right. I'll make the path to the icons customizable as for the other widgets (I'll post a message here when it's done). For now I added a validation - if folder `/usr/share/icons/Arc/status/symbolic/` doesn't exist there will be a error notification with details.

**Comment by streetturtle** [comment]
Path to the icons is now cusomizable. However the widget uses 12 different icons and expects the same name format as in the Arc icons. So in case you want to change icons and they have a different name format you'll need to rename them. I think adding icon names in the config would be not very nice solution, as there are too many of them.

**Comment by georgerabus** [comment]
> Path to the icons is now cusomizable. However the widget uses 12 different icons and expects the same name format as in the Arc icons. So in case you want to change icons and they have a different name format you'll need to rename them. I think adding icon names in the config would be not very nice solution, as there are too many of them.

where to get the icons from?
