### ISSUE TITLE
attempt to index nil value

### ISSUE THREAD

**Issue by Yar-R** [streetturtle/awesome-wm-widgets#103]
I am trying to make these widgets work:
`local volumearc_widget = require("awesome-wm-widgets.volumearc-widget.volumearc")
local batteryarc_widget = require("awesome-wm-widgets.batteryarc-widget.batteryarc")
local cpu_widget = require("awesome-wm-widgets.cpu-widget.cpu-widget")` 

all of them raise the same error:

> Dec 12 00:52:12 ... /usr/lib/gdm3/gdm-x-session[1279]: error while running function!
> Dec 12 00:52:12 ... /usr/lib/gdm3/gdm-x-session[1279]: stack traceback:
> Dec 12 00:52:12 ... /usr/lib/gdm3/gdm-x-session[1279]:         /usr/share/awesome/lib/wibox/widget/base.lua:461: in upvalue 'drill'
> Dec 12 00:52:12 ... /usr/lib/gdm3/gdm-x-session[1279]:         /usr/share/awesome/lib/wibox/widget/base.lua:493: in upvalue 'drill'
> Dec 12 00:52:12 ... /usr/lib/gdm3/gdm-x-session[1279]:         /usr/share/awesome/lib/wibox/widget/base.lua:529: in function 'wibox.setup'
> Dec 12 00:52:12 ... /usr/lib/gdm3/gdm-x-session[1279]:         /home/.../.config/awesome/rc.lua:231: in local 'func'
> Dec 12 00:52:12 ... /usr/lib/gdm3/gdm-x-session[1279]:         /usr/share/awesome/lib/awful/screen.lua:438: in function 'awful.screen.connect_for_each_screen'
> Dec 12 00:52:12 ... /usr/lib/gdm3/gdm-x-session[1279]:         /home/.../.config/awesome/rc.lua:204: in main chunk
> Dec 12 00:52:12 ... /usr/lib/gdm3/gdm-x-session[1279]: error: /usr/share/awesome/lib/wibox/widget/base.lua:461: attempt to index a nil value (local 'layout')

**Comment by streetturtle** [comment]
Can you share your rc.lua?

**Comment by Yar-R** [comment]
https://pastebin.com/VYcyQ3RK

**Comment by streetturtle** [comment]
When you use widget in wibox, you need to add a parentheses, as it's a function, not an object:

```lua
        mytextclock,
        cpu_widget(),
        batteryarc_widget(),
        volumearc_widget(),
        s.mylayoutbox,
        },
    }
...

Please pull the latest changes also, just in case and let me know if it helped.

**Comment by Yar-R** [comment]
works now, thanks
