### ISSUE TITLE
Weather widget is not accepting args from config file

### ISSUE THREAD

**Issue by jeetelongname** [streetturtle/awesome-wm-widgets#106]
when giving your weather widget a city argument in my **theme.lua** file (this is where i have put my wibox configuration) the file does not accept the argument and defaults. this has not been a problem with other widgets that i have used. i changed the default in the **weather.lua** file and then my weather data was used. if this is too little information i am happy to give more.

**Comment by streetturtle** [comment]
Hm, that's strange, I've just tried with several cities from different countries (`San Franciso,us`, `Vancouver,ca`, `Punta Cana,do`) and it worked well. What city are you setting? Note that after the city name there should be a ISO 3166 country code divided by comma.

**Comment by jeetelongname** [comment]
yeah i did not realize that i needed to put in quotation marks this was my fault. Sorry
