### ISSUE TITLE
cpu-widget cannot handle ps process names having 'space' 

### ISSUE THREAD

**Issue by bucketsize** [streetturtle/awesome-wm-widgets#116]
In
> awesome-wm-widgets/cpu-widget/cpu-widget.lua
> cmd = string.sub(cmd,0, 300)

cmd, comm, etc is nil for lines like:

>  18398 Web Content      0.1  1.8 /usr/lib/firefox/firefox -contentproc -childID 14 -isForBrowser -prefsLen 9159 -prefMapSize 207639 -parentBuildID 20200120145402 -greomni /usr/lib/firefox/omni.ja -appomni /usr/lib/firefox/browser/omni.ja -appdir /usr/lib/firefox/browser 3466 true tab

This does not cause any errors to be printed in console or notification, just the cpu box remains inactive.

Could be solved (partially having partial / incorrect cmd, comm) with having ps output cmd, comm in the end, would make parsing using :match more easier. But haven't tried. Will do when time permits

**Comment by streetturtle** [comment]
Fixed by https://github.com/streetturtle/awesome-wm-widgets/commit/249ac4d688aa047f03e8232d5b932a517641e3e1
