### ISSUE TITLE
syntax for awesome 4.x

### ISSUE THREAD

**Issue by alvesadrian** [streetturtle/awesome-wm-widgets#12]
cloned the repo into ~/.config/awesome/widgets
but the syntax in all of the readme files didnt work with awesomwm 4.x versions
tried volume and battery

**Comment by Taddic** [comment]
What is the problem you have exactly? I am using these widgets (battery and volume) with 4.2 and before that with 4.0 and it has been working properly for me.

**Comment by streetturtle** [comment]
If you cloned repo under **~/.config/awesome/widgets** then the import should be the following:
`require("widgets.awesome-wm-widgets.battery-widget.battery")`. Feel free to reopen the issue, I would be happy to help.
