### ISSUE TITLE
CPU widget causes high cpu usage

### ISSUE THREAD

**Issue by madprops** [streetturtle/awesome-wm-widgets#120]
When I activate the widget the awesome process cpu usage goes up to an average of 10%
Removing the widget reduces the cpu usage.
Maybe the interval is too aggressive?

**Comment by madprops** [comment]
Tested just now with the latest git awesome, cpu seems a lot lower, at around a constant 1.5%, I think still high considering having htop open I use around 0.5%

**Comment by imabuddha** [comment]
I'm running the following version from my disto (not the latest git) and also see the usage that @madprops mentioned with the default timeout. I set that to 10 which helps a lot. Hopefully either you can improve this widget's efficiency. I suppose that if there are other significant advantages then I could start using the latest git version of awesome.

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

BTW, thank you very much for making this **awesome** project! Your doc, imgs, etc. are all so much better than most.

**Comment by streetturtle** [comment]
This should be fixed now
