### ISSUE TITLE
Volumearc rotate incorrectly

### ISSUE THREAD

**Issue by Avorezo** [streetturtle/awesome-wm-widgets#122]
Very cool widgets. Thanks so much for them.
I noticed a flaw in the Volumearc. With increasing volume, the slider increases counterclockwise. Can this be fixed? And inside there is no volume icon.

**Comment by streetturtle** [comment]
Thanks!
Some time ago I had a OnePlus X, it ran Oxygen OS, which allowed to change the battery icon. One of the options were the very similar arcchart, and it was increasing the same way, counterclockwise. Now I am not sure if it was the right decision. I need some time to think about it)
