### ISSUE TITLE
Volume widget doesn't update

### ISSUE THREAD

**Issue by d9d6ka** [streetturtle/awesome-wm-widgets#124]
#118
> Everything works perfectly when I change the volume level by scrolling with the hovering cursor. But when I change the volume level using keyboard shortcuts, the icon would not update.

I'm terribly sorry for (maybe) necroposting, but the initial problem still occurs for me. The icon in tray updates only by mousebutton actions, not by keyboard shortcuts.

**Comment by d9d6ka** [comment]
My system is:
Void Linux i686, fully upgraded
awesome 4.3
pulseaudio (also had to replace amixer by pactl)

**Comment by utix** [comment]
Can you share your rc.lua configuration relative to the keymapping ?
something like:
```
awful.key(
    {},
    'XF86AudioRaiseVolume',
    volume_widget.raise,
    {description = 'volume up', group = 'hotkeys'}
  ),
  awful.key(
    {},
    'XF86AudioLowerVolume',
    volume_widget.lower,
    {description = 'volume down', group = 'hotkeys'}
  ),
  awful.key(
    {},
    'XF86AudioMute',
    volume_widget.toggle,
    {description = 'toggle mute', group = 'hotkeys'}
  )```

**Comment by d9d6ka** [comment]
Sure. `volume_widget.update()` command is related to lain's volume widget.

`awful.key({}, "XF86AudioRaiseVolume", function()
        os.execute("pactl set-sink-volume @DEFAULT_SINK@ +5%")
        -- lain volume widget update
        volume_widget.update()
    end, {description = "Raise volume", group = "awesome"}),
    awful.key({}, "XF86AudioLowerVolume", function()
        os.execute("pactl set-sink-volume @DEFAULT_SINK@ -5%")
        -- lain volume widget update
        volume_widget.update()
    end, {description = "Lower volume", group = "awesome"}),
    awful.key({}, "XF86AudioMute", function()
        os.execute("pactl set-sink-mute @DEFAULT_SINK@ toggle")
        -- lain volume widget update
        volume_widget.update()
    end, {description = "Mute sound", group = "awesome"})`

**Comment by utix** [comment]
Can you try with this branch https://github.com/utix/awesome-wm-widgets/tree/volume_KeysBinding ?
If this fix your issue, I will rebase it, finish it and do the pull request

**Comment by d9d6ka** [comment]
> Can you try with this branch https://github.com/utix/awesome-wm-widgets/tree/volume_KeysBinding ?
> If this fix your issue, I will finish the revamp and do the pull request

Unfortunately, `amixer` doesn't connect to pulseaudio in my case, so I've had to rewrite volume modification commands. But despite this everything works like a charm! Thank you a lot!

Wish I were more experienced in Lua! :)

My slightly modified version: https://github.com/d9d6ka/awesome-wm-widgets/blob/master/volume-widget/volume-utix.lua
