### ISSUE TITLE
batteryarc-circle: no text

### ISSUE THREAD

**Issue by Pascal3366** [streetturtle/awesome-wm-widgets#141]
Hello, I am trying to get the batteryarc circle widget to work for hours now.

I set it up like this:

batteryarc_widget({
                font = 'Play 6',        
                show_current_level = true,
                arc_thickness = 1,
                main_color = beautiful.fg_color,
                bg_color = '#ffffff11',
                charging = '#43a047',
                low_level_color = '#e53935',
                medium_level_color = '#c0ca33',
                enable_battery_warning = true,
            }),

I even tried it with default settings.

However no font / text is showing up and no charging color.

I installed the Play fonts as follows:

$ fc-list | grep Play                                                    
/usr/share/fonts/play/Play-Bold.ttf: Play:style=Bold
/usr/share/fonts/play/Play.ttf: Play:style=Regular
/usr/share/fonts/play/Play-Regular.ttf: Play:style=Regular

I don't know if this is a bug or a misconfiguration, but I hope it can be resolved.

**Comment by streetturtle** [comment]
Could you please post the output of `acpi -i`. I think there might be a bug.

**Comment by Pascal3366** [comment]
Battery 0: Discharging, 32%, 00:53:51 remaining
Battery 0: design capacity 2181 mAh, last full capacity 1693 mAh = 77%
Battery 1: Unknown, 5%
Battery 1: design capacity 4555 mAh, last full capacity 4129 mAh = 90%

**Comment by Pascal3366** [comment]
However the charging color is now green after some time plugged, but it does not seem to go away after removing the plug

**Comment by streetturtle** [comment]
Yep, there is a bug. There is some fancy logic to calculate battery status using battery design/actual capacities introduced by one of the contributor, but it doesn't work for some reason. I'll remove it and in case of more than one battery will display the most charged one. Will push the fix today/tomorrow. 
Thanks!

**Comment by streetturtle** [comment]
Don't think compton can cause it, I have many different widgets and I'm using compton - no issues so far
