### ISSUE TITLE
Low battery notification if one battery is low

### ISSUE THREAD

**Issue by Pascal3366** [streetturtle/awesome-wm-widgets#144]
Hi, thanks for fixing the bug with the battery percentage and colors. It works now.

However there seems to be another bug with the batteryarc widget.

If you have two batteries and one of them dies (Bat1) then Bat0 is used but the widget is spamming a low battery notification the whole time because one battery is low.

I am not sure if this is a bug in the widget or in awesome itself, or in the Holo Theme, because I am not sure where the notification "Battery low. Plug the cable!" is coming from.

**Comment by Pascal3366** [comment]
Ok I just saw that this issue is coming from the bat lain widget maybe it is not the fault of your batteryarc widget

**Comment by streetturtle** [comment]
The batteryact sends only this warning notification: ![warning](https://github.com/streetturtle/awesome-wm-widgets/blob/master/batteryarc-widget/warning.png) so it seems the one you have comes from somewhere else.

**Comment by Pascal3366** [comment]
yes this battery warning just popped up at the right time :dagger: 

so it seems like this issue is coming from awesome itself or my theme so i guess I have to disable the other warning
