### ISSUE TITLE
Weather widget doesn't work

### ISSUE THREAD

**Issue by HishamAHai** [streetturtle/awesome-wm-widgets#154]
I'm on Arch with latest kernel (also tried with the lts kernel) and git version of awesome
I've installed the json.lua and lua-socket from the official repositories of arch and have arc icons installed and can't get the weather widget to work.
Other widgets like the volume and spotify do work

**Comment by azamaschikov** [comment]
I have this problem too.

My awesome:
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

```
And lua sockets:
```
Repository      : community
Name            : lua-socket
Version         : 20190219-1

```
Widget is starting, but weather don't showing. Direct API-link to openweathermap.org work correctly.

**Comment by HishamAHai** [comment]
Here is the log from my machine
`2020-06-03 11:15:15 W: awesome: awful.widget.graph has been renamed to wibox.widget.graph.
stack traceback:
	/usr/share/awesome/lib/gears/debug.lua:107: in function 'gears.debug.deprecate'
	/usr/share/awesome/lib/gears/debug.lua:158: in field 'graph'
	/home/hisham/.config/awesome/rc.lua:178: in local 'new_handler'
	/usr/share/awesome/lib/awful/screen.lua:1023: in function </usr/share/awesome/lib/awful/screen.lua:1020>
	[C]: in field 'connect_signal'
	/home/hisham/.config/awesome/rc.lua:67: in main chunk`

**Comment by streetturtle** [comment]
It seems that I have the same issue, from time to time it's just not showing up. I'll investigate what's wrong there and let you know.

**Comment by streetturtle** [comment]
Can you please try with latest version (if you are still interested ;) ) Sorry for the late reply.
