### ISSUE TITLE
Volume widget : attempt to index a nil value (field 'iconbox')

### ISSUE THREAD

**Issue by xt0ph** [streetturtle/awesome-wm-widgets#156]
Hi,
I just installed your widgets and added the volume-widget to my menu bar.
I have the following error with my mouse wheel:
```
E: awesome: Error during a protected call: .../volume-widget/volume.lua: 69: attempt to index a nil value (field 'iconbox')
```
Regards.

**Comment by streetturtle** [comment]
I have rewritten the volume widget, could you please try again, and reopen this issue if it doesn't work out.
