### ISSUE TITLE
Spotify widget breaks playback

### ISSUE THREAD

**Issue by fuzebox1** [streetturtle/awesome-wm-widgets#158]
I've implemented a bunch of your widgets in my theme lua and it's all working great. Except for the spotify widget.
I have sp in path and the widget is "installed" correctly afaik.
But with it loaded spotify at first plays 1 sec then pauses, and after that when i click the widget, or the play pause in spotify nothing happens. Play/pause changes but nothing plays. I also noticed the system chugging a little.
Im new to LUA so i cant tell what the code is doing exactly.

Also, any chance you could make a cpu temp widget? The lain one does'nt update or show correct temps :).

**Comment by streetturtle** [comment]
Are you using the latest master version? I updated it just yesterday. If not, try latest master, if yes, could you please rollback to this commit: https://github.com/streetturtle/awesome-wm-widgets/commit/c55c60a7d0e9630be86663f2b59a8d0b020dbe43 and try again. 
And if possible can you send awesome's logs, if you have any, when this happens - maybe there's something interesting there (here is how to get them, in case you don't know: https://pavelmakhov.com/2020/04/awesome-wm-development-setup/).

Regarding the cpu-temp widget, I can make a widget which shows just a current temperature, but I thought maybe showing the temperature the same way as in the cpi-widget - with a graph? What do you think?

**Comment by fuzebox1** [comment]
I have tried this master and the one from a few days ago. No dice.
I like the idea of a graph for cpu temp! Much more useful than just current.
I augmented your great cpu graph with the current % use, does'nt look as pretty as i'd like but ricing aint done yet.

I launched awesome in Xephyr and well, thank you for that - found a bunch of errors in my config i can easily fix. But nothing at all on spotify.

**Comment by fuzebox1** [comment]
On a side note i noticed your python scripts for the mail widget are outdated, ill re write them in py3 and do a pull tomorrow if thats alright. Maybe i can add multiple mailboxes too.

**Comment by streetturtle** [comment]
Yep, there is something not right, just tried the latest version of spotify installed from a snap, and it stops playing when `sp status` is executed. Will investigate further.

**Comment by streetturtle** [comment]
I found the problem, you should use `sp` from here https://gist.github.com/fa6258f3ff7b17747ee3 - it's a fork with few additions. 

Just to give more context - I forked the `sp` script from here https://gist.github.com/wandernauta/6800547 a long time ago and made few modifications there, and used it in README. Recently I though that I might not need to use my fork, but use the original version, which didn't work out - when `sp status` is executed, spotify stops playing. So I reverted my recent change to the widget's README.
