### ISSUE TITLE
unable to get any widget to run

### ISSUE THREAD

**Issue by Khorkhe** [streetturtle/awesome-wm-widgets#16]
installed Arc font under ~/.icons, cloned the repo under ~/.config/awesome, required the widget and used it, though nothing gets displayed.

not sure what i'm doing wrong, i do have equivalent battery and volume working from elsewhere. any suggestions?

awesome -version: 4.2

**Comment by streetturtle** [comment]
By default it expects icons to be in **/usr/share/icons/Arc/status/symbolic/**. But you can change that, [here](https://github.com/streetturtle/awesome-wm-widgets/blob/master/volume-widget/volume.lua#L6) for the volume widget and [here](https://github.com/streetturtle/awesome-wm-widgets/blob/master/battery-widget/battery.lua#L10) for the battery widget. I would also suggest to use the full path there (like **/home/username/.icons/Arc/status/symbolic/**) as I am not sure that Lua would understand **~/.icons**-like path.  
Let me know if it works.

**Comment by streetturtle** [comment]
Feel free to reopen this issue, I would be happy to help!
