### ISSUE TITLE
Spotify popup album art huge

### ISSUE THREAD

**Issue by fuzebox1** [streetturtle/awesome-wm-widgets#162]
Just a little annoyance i tried to solve myself but was unable.
The notify popup when discord changes songs - the album art is very large, is there a simple way to reduce it's size?

**Comment by prathamesh610** [comment]
Yes i too have that issue. Guess that may not be the spotify widget issue but might be mpd widget issue. I tried changing things but no luck!

**Comment by streetturtle** [comment]
Hi! Notifications comes from a spotify client, not from a widget. However it's possible to customize it. I would suggest this workaround: https://gist.github.com/alepmaros/847020a2e40972e178648a4dc2288e83

**Comment by fuzebox1** [comment]
This worked, thank you!
