### ISSUE TITLE
net_widget improvement

### ISSUE THREAD

**Issue by fuzebox1** [streetturtle/awesome-wm-widgets#163]
I like to have network interface RX and TX in my bar, but i find your widget rather unreadable at a glance. I'm not even sure if it provides bytes or kb, and what actually happens when i change the formatting to print 4 digits instead of 6 with the dot.

Anyways, i recently wrote a unit converter in python for one of my projects:

`UNITS = [ "k", "M", "G", "T", "P", ]`
`def human_size(s):`
`    for u in UNITS:`
`        s = s / 1024 # Or 1000 if you lean that way`
`        if s < 1024:  # --""--`
`            return "{0:.0f}{1}".format(s, u) + "B"`

Would it be possible to do something like this for your widget in order to provide the RX and TX bytes in the most relevant format, ie kB, MB, GB etc?

I hope i make myself understandable here :)

**Comment by streetturtle** [comment]
Hi! Mmm, what widget are you talking about? I have a feeling that you missed the repo)

**Comment by fuzebox1** [comment]
Oh wow, sorry about that - i use mostly your widgets, but the net_widgets is the lain one!
You dont happen to have plans for a functional widget like that? :)

**Comment by streetturtle** [comment]
Not yet, but I was thinking about it. Could you please create another issue requesting a net widget) I'll be happy to make one =)
