### ISSUE TITLE
Github widget install

### ISSUE THREAD

**Issue by fuzebox1** [streetturtle/awesome-wm-widgets#166]
I attempted to install the github activity widget yesterday but was unable to get it working with the documentation provided.

Attempted to install it like the other widgets, initializing it with a local and running it in the s.mywibox:setup.
I put the provided code in as well, but i guess i dont understand what it does well enough to know where to put it.

Can you provide example code snippets from your rc.lua (or theme.lua)?

**Comment by streetturtle** [comment]
Oh, I see, I forgot to put an example section on the readme. My bad. I'll update it.
You just need to add following, as usual:

```lua
local github_activity_widget = require("awesome-wm-widgets.github-activity-widget.github-activity-widget")
...
s.mytasklist, -- Middle widget
	{ -- Right widgets
    	layout = wibox.layout.fixed.horizontal,
		...
        github_activity_widget{
            username = 'fuzebox1',
        },		...      
```
