### ISSUE TITLE
Volume widget can't switch between output devices

### ISSUE THREAD

**Issue by ExpectoPatrom** [streetturtle/awesome-wm-widgets#182]
When you have various output devices (for example a gpu and the headphones through the motherboard) you can switch the current output channel, it would be nice to can change, or modify both at the same time for practicity

**Comment by streetturtle** [comment]
Hi! Sorry for such late reply. 
I am reimplementing the volume widget, could you please try this one: https://github.com/streetturtle/awesome-wm-widgets/tree/master/experiments/volume by adding it to your rc.lua:
```lua
local volume = require('awesome-wm-widgets.experiments.volume.volume')
```

And then define the widget the following way:

```lua
volume_widget {
  widget_type = 'icon_and_text' -- or any other supported type, check README
}
```
