### ISSUE TITLE
Wigets get updated slowly

### ISSUE THREAD

**Issue by Nolkaloid** [streetturtle/awesome-wm-widgets#183]
For example, I'm using the volume arc widget, when I click to mute it I takes around 1s to switch to the muted state (red color).

**Comment by streetturtle** [comment]
I am working on a new volume widget, which has some cool features, and is more responsive. Could you please try it out. Currently it's under **/experiments** folder. When it's ready, I'll deprecate existing ones (volume, volumebar and volumearc). 

To try it, initialize it:
```lua
local volume_widget = require('awesome-wm-widgets.experiments.volume.volume')
```
And then use it the following way:
```lua
volume_widget_arc{
  widget_type = 'arc'
}
```

**Comment by Nolkaloid** [comment]
Works great!
