### ISSUE TITLE
Yandex no longer provides free API keys

### ISSUE THREAD

**Issue by vevais** [streetturtle/awesome-wm-widgets#184]
I wanted to use the translation widget, only to find out that there are no free API keys being provided by the site anymore. Will it be possible to port the widget to another provider?

**Comment by streetturtle** [comment]
Oops, missed that, haven't used it for a while.

Language Translator from IBM Cloud seems to be a good free alternative: https://cloud.ibm.com/catalog/services/language-translator
Any objection? If not, I'll switch to it in the coming weeks.
