### ISSUE TITLE
[Feature request] [volume-widget] Display volume level like brightness-widget and battery-widget

### ISSUE THREAD

**Issue by joaopauloalbq** [streetturtle/awesome-wm-widgets#185]
![2020-09-06-163159_1920x1080_scrot](https://user-images.githubusercontent.com/9905202/92333803-be636b00-f05e-11ea-839c-71d18ebf8c3b.png)

**Comment by streetturtle** [comment]
I am working on a new "ultimate" volume widget, as currently there are 3 similar volume widgets with different "ui". New widget comes with few predefined "UIs", one of the is exactly what you requested.
Could you please try to use it: https://github.com/streetturtle/awesome-wm-widgets/tree/master/experiments/volume

You'll need to add it to your rc.lua as usual
```lua
local volume = require('awesome-wm-widgets.experiments.volume.volume')
``` 
And then define a widget the following way:
```lua
volume_widget {
  widget_type = 'icon_and_text'
}
```

I'll add more information to the README soon. 

Thanks!

**Comment by joaopauloalbq** [comment]
It's working well but I had to change the volume control from `volume_widget.lower` to `awful.spawn("amixer -q sset Master 5%- unmute", false)` and so on. I I also didn't find an option to change the margins like the battery widget. 
Thank you!

**Comment by streetturtle** [comment]
I forgot about exposing volume control methods by the widget, thank you for reminding) I've added them, so you can define your shortcuts this way:

```lua
awful.key({ modkey }, "]", function() volume_widget:inc() end),
awful.key({ modkey }, "[", function() volume_widget:dec() end),
awful.key({ modkey }, "\\", function() volume_widget:toggle() end),
```

Regarding the margins, I don't think they are needed, as the widget is added to the fixed layout, which has a `spacing` property, which defines the distance between widgets. In other words, it's container's responsibility to take care of the margins of it's children.
