### ISSUE TITLE
Watch intervals triggers high cpu usage

### ISSUE THREAD

**Issue by cgsimmons** [streetturtle/awesome-wm-widgets#187]
Many of these are set to `1` second and just destroys cpu utilization. Offenders I witnessed were the volumearc-widget, batterarc-widget, cpu-widget (even though it's 15s). Would probably be good to just make this configurable with more sane defaults (even the watch default is 5s)

**Comment by cgsimmons** [comment]
Also, not trying to sound harsh. Really appreciate the widgets!

**Comment by streetturtle** [comment]
Thanks for raising an issue!
Resolved by #188
