### ISSUE TITLE
weather widget not working?

### ISSUE THREAD

**Issue by jshamg** [streetturtle/awesome-wm-widgets#19]
I put the json.lua in awesome in ./config/awesome/ and the Arc folder in /user/share/icons/
I edited in the weather.lua my city and my api code (both are working i checked it via the browser at http://api.openweathermap.org/data/2.5/weather?q= and i got all the Output for Berlin and my key is working) in the rc.lua I added the line require("awesome-wm-widgets.weather-widget.weather") and in the wibar 

        s.mytasklist, -- Middle widget
        { -- Right widgets
            layout = wibox.layout.fixed.horizontal,
            mykeyboardlayout,
	    weather,
            wibox.widget.systray(),
	    cpu_widget,
            mytextclock,
            s.mylayoutbox,
        },

the widget is just not showing up. i don't have no erros i think because i got an error while i didn't entered my key...
ps.i hate markup i don't know how to make new paragraphs haha

greetings from germany!

**Comment by streetturtle** [comment]
Hi from :canada: :)
I think the problem is in your **rc.lua**, the widget's name is `weather_widget`, not `weather`. Let me know if it worked.

**Comment by jshamg** [comment]
works perfectly, i thought the widget name was the name of the file with .lua ending in the folder but its the same as the folder name... very cool widget! thxx 
greetings!
