### ISSUE TITLE
CPU widget performance improvement

### ISSUE THREAD

**Issue by voider1** [streetturtle/awesome-wm-widgets#191]
Currently the CPU widget cats into grep, however grep has the capability to read from a file, like so:

```sh
grep '^cpu.' /proc/stat ; ps -eo '%p|%c|%C|' -o '%mem' -o '|%a' --sort=-%cpu | head -11 | tail -n +2 
```

Also consider using sh instead of bash for compatibility and performance.

**Comment by streetturtle** [comment]
Thank for raising an issue!
I fixed it some time ago, but forgot to close the issue. Didn't think about sh, now trying to use it everywhere, thanks!
