### ISSUE TITLE
VitalyGorbachev icons need .png versions

### ISSUE THREAD

**Issue by nedludd** [streetturtle/awesome-wm-widgets#194]
The code requires a .png icon, but only .svg files are provided in the VitalyGorbachev icons directory.

Great addition!!  Keep up the good work!

**Comment by streetturtle** [comment]
There is an `icons_extension` parameter, which specifies the file extension of icons which is set to `.svg` by default. 
Thanks! :+1:

**Comment by nedludd** [comment]
Seems to be `.png` by default:

Line 139 in `weather.lua`:

`local icons_extension = args.icons_extension or '.png'`

**Comment by streetturtle** [comment]
oh, yeah, you right, sorry for that )
