### ISSUE TITLE
Volume widget has different icons on multiple monitors

### ISSUE THREAD

**Issue by dylanpjx** [streetturtle/awesome-wm-widgets#197]
First monitor volume widget reflects the correct icon while second monitor volume widget always show `volume = 0` icon

**Comment by robstoll** [comment]
I have noticed this as well. It seems to me this is a regression. I have just pulled latest master. Unfortunately from a quite old commit (0fb3558 1 year, 4 months ago) so there are plenty commits in question I guess.

**Comment by TheCarrotCR** [comment]
You can put creation of widget outside of wibar setup:

```
volume_widget_widget = volume_widget({display_notification = true, volume_audio_controller = 'alsa_only'})
...
 s.mytasklist, -- Middle widget
        { -- Right widgets
            ...
            volume_widget_widget,
...
```

- after doing so it works like a charm. So problem appears only on creating multiple instances of widget.

**Comment by robstoll** [comment]
Works for me as well :)

**Comment by Tert0** [comment]
Works for me too.
Thanks

**Comment by streetturtle** [comment]
Thanks! I'll update the readme with this information.

**Comment by Tert0** [comment]
@streetturtle Made a Pull Request for the new Readme
