### ISSUE TITLE
integration with pasystray

### ISSUE THREAD

**Issue by muellert** [streetturtle/awesome-wm-widgets#199]
This is a feature request.

I would very much like this widget to be integrated with pasystray, so I do not have two icons for audio in my systray. I like the pasystray icon, because it also indicates the volume and allows for configuring the various sources, sinks etc., but I need the volume widget, because it allows keyboard control. It would be nice to save on screen real estate.

**Comment by Ryuno-Ki** [comment]
Leaving the link to the source code here for reference: https://github.com/christophgysin/pasystray

**Comment by streetturtle** [comment]
Perfect timing! I'm currently working on this:)

I already have a widget with a drop-down which allows to select a sink/source. Next step is to add a volume widget to it. I'll push what I have in experiments folder later today/tomorrow.

**Comment by muellert** [comment]
Dear streetturtle, thanks a lot for your efforts! When I asked, I was just thinking of something (hopefully) cheap that would combine your keyboard control with pasystray, so as to use only one slot in the systray. Not sure whether that's possible, though.

**Comment by streetturtle** [comment]
Hm, I don't think I get what you mean by "your keyboard control". The keyboard shortcuts are setup in rc.lua, and completely separated from the widget. So you can remove the volume widget, and shortcuts will still work.

Just for info, I am currently trying to make an "ultimate" volume widget, which will allow changing sources/sinks by right clicking on the widget:
![Selection_124](https://user-images.githubusercontent.com/9363150/97812360-d0bce800-1c4e-11eb-8dc4-f1aebde26782.png)
