### ISSUE TITLE
volumebar not showing up

### ISSUE THREAD

**Issue by jshamg** [streetturtle/awesome-wm-widgets#20]
The regular volume icon works pretty well, but the volumebar widget is just not showing any bar... the widget is there (i can see it because there is a bigger space between my ":") and scrolling and clicking works i can test it in alsamixer. Maybe you have an idea...

PS.: for an update i would change your `amixer -D pulse sset Master (...)` in `amixer set Master (...)` because somehow it is faster and i got really weird side effects using your version. The level of the speakers left and right were unstable and were changing while changing the volume by scrolling. Even the levels of left and right didn't stayed equal. sometimes left was at 50% and right at 100% and the other way around, it seems like it depends on the scrolling speed... Same happened with using `amixer -D pulse sset Master` for keyboard shortcuts.
With changing that i would change `amixer -D pulse sget Master` to `amixer get Master` , too.

Again greetings from Berlin, germany 
and big thanks for the nice widgets!
Josh

**Comment by jshamg** [comment]
p.s.: the volumearc works without a problem...

**Comment by streetturtle** [comment]
Regarding the current volume level, on my laptop `amixer get Master` returns much less information than `amixer -D pulse sget Master`:

```bash
$ amixer get Master
Simple mixer control 'Master',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback 0 - 127
  Mono: Playback 104 [82%] [-11.50dB] [on]
$ amixer -D pulse sget Master
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 42237 [64%] [on]
  Front Right: Playback 42237 [64%] [on]
```
Same for setting volume level. So I think it depends on the laptop/PC. I'll mention it in README.

**Comment by jshamg** [comment]
You are absolutely right. yesterday I ported everything to my thinkpad and I had to to set an a ~/sound.conf in order use direct commands like amixer get mixer and the regular toggle amixer set Master toggle didn't work. instead all your commands worked great. I don't know, the other laptop always has issues because of its strange amd-proz and ati-graf... I think your solution is better. But the volume bar isn't working, too haha :) . everything else works!

**Comment by streetturtle** [comment]
Hmm, that's strange. I would recommend to change colors, just to be sure that it's not an issue. Also could you please tell which version of Awesome you're using?

**Comment by jshamg** [comment]
I'm gonna figure everything a little bit out and I will answer when I find out what was wrong. I use awesome 4.0 btw. I have another problem with the battery widget wich pops up an alert when the battery is critcal. The script is a loop thats why the popup appears over and over again while I tryed to fix it, it stopped appearing over and over again. Now I dont know If it was a simple error or something else is wrong. Maybe you have an idea... greetings!

**Comment by streetturtle** [comment]
I agree, the popping up warning is annoying :) I raised an [issue](https://github.com/streetturtle/awesome-wm-widgets/issues/23) for that. I think I'll fix it some time soon.

**Comment by Goomb** [comment]
```lua
volumebar_widget = wibox.widget {
    max_value = 1,
    forced_width = 50,
    forced_height = 1,
    paddings = 0,
    border_width = 0.5,
    color = bar_color,
    background_color = background_color,
    shape = gears.shape.bar,
    clip = true,
    margins       = {
        top = 9,
        bottom = 10,
    },
    set_value = function(self, value)
        self.value = value
    end,
    widget = wibox.widget.progressbar
}
```
Change to `top = 9,` fix that. The line is too thin.

**Comment by streetturtle** [comment]
I've add this to the [readme](https://github.com/streetturtle/awesome-wm-widgets/blob/master/volumebar-widget/README.md) of the volumebar widget. Thanks for help!
