### ISSUE TITLE
Github contributions api changed

### ISSUE THREAD

**Issue by GlowSquid** [streetturtle/awesome-wm-widgets#203]
Looks like GitHub changed some CSS variables, and the [github-contributions-chart ](https://github.com/sallar/github-contributions-chart) repo isnt updated.
Caused my .xsession-errors to grow to 16 GB. Had to temporary disable the widget.

**Comment by GlowSquid** [comment]
Works perfectly. Thanks a lot!

**Comment by streetturtle** [comment]
I'm also adding themes now. Will post here once finished.

**Comment by streetturtle** [comment]
Just for info, I've added themes to the widget!
