### ISSUE TITLE
What's the best way to support this project financially?

### ISSUE THREAD

**Issue by robstoll** [streetturtle/awesome-wm-widgets#212]

**Comment by streetturtle** [comment]
Wow, didn't expect this question :)
I've added a Support section to the readme: https://github.com/streetturtle/awesome-wm-widgets#support
Thanks!

**Comment by robstoll** [comment]
Thanks for the info :+1: 
As hint, you can add a GitHub sponsors button to the project -> https://github.com/streetturtle/awesome-wm-widgets/pull/214

**Comment by robstoll** [comment]
@streetturtle we sponsor you now 🙂
We thought about a bit more though. Would you mind adding a few more options?

**Comment by streetturtle** [comment]
Wow, can't believe it =) I've added more tiers.
Thank you!

**Comment by robstoll** [comment]
You're welcome :)
