### ISSUE TITLE
Feature: Make mouseover optional

### ISSUE THREAD

**Issue by tasmo** [streetturtle/awesome-wm-widgets#215]
To show the battery level I prefer to click on the widget or use a shortcut.

For the `batteryarc_widget` the mouseover is hardcoded without an option:

https://github.com/streetturtle/awesome-wm-widgets/blob/abed865eff7c0c2dc5c70108857e8113d8ab2dfc/batteryarc-widget/batteryarc.lua#L136-L141

I tried to use a `disconnect_signal` without any luck yet.

**Comment by streetturtle** [comment]
Thanks for the issue! :+1: 
I've added a `show_notification_mode` option, which may have following values: 
 - `on_hover` - show notification on mouse hover, which is default
 - `on_click` - show notification on mouse click
 - `off` - don't show notification.
So for you case you have to define the widget a following way:
```lua
batteryarc_widget{
    show_notification_mode = 'on_click'
}
```

**Comment by tasmo** [comment]
Wow, this is a nice solution. Many thanx for the awesome response!
