### ISSUE TITLE
Logout widget not installing

### ISSUE THREAD

**Issue by massdregs** [streetturtle/awesome-wm-widgets#219]
I have not done anything other than write the line
`  local logout = require("awesome-wm-widgets.logout-widget.logout")`

I saved the config, then I restarted awesome. Awesome threw the generic failed to connect to screen error.

**Comment by streetturtle** [comment]
Have you cloned the https://github.com/streetturtle/awesome-buttons repo?

**Comment by streetturtle** [comment]
Feel free to reopen
