### ISSUE TITLE
Update README.md for translate-widget

### ISSUE THREAD

**Issue by ReporterNV** [streetturtle/awesome-wm-widgets#220]
The widget now uses a solution from IBM, the [`README.md`](https://github.com/streetturtle/awesome-wm-widgets/blob/master/translate-widget/README.MD) file is still for Yandex.

И можно ли писать issue не только на английском языке?

**Comment by streetturtle** [comment]
Good catch, thanks! I completely forgot about it. 
I'll leave here some details, just for reference: 

```
awful.key({ modkey }, "c", 
        function() translate.launch{
            api_key = '<api-key>',
            url = 'url'
        } end,
        { description = "run translate prompt", group = "launcher" })
```
`api-key` should be generated on this page: https://cloud.ibm.com/iam/apikeys
`url` should be taken from the Language-Translator's page

**Comment by streetturtle** [comment]
Done! Thanks again for letting me know! Сорян в общем =)
