### ISSUE TITLE
Volume arc not displayed

### ISSUE THREAD

**Issue by smaslovski** [streetturtle/awesome-wm-widgets#231]
Hi,

I am on current Debian testing (bullseye) with the following version of awesome wm: 

```
$ awesome --version
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 ```

The volumearc widget would not show the volume arc. The following patch resolves the issue:

```
diff --git a/volumearc-widget/volumearc.lua b/volumearc-widget/volumearc.lua
index a62abde..4f0377a 100644
--- a/volumearc-widget/volumearc.lua
+++ b/volumearc-widget/volumearc.lua
@@ -74,7 +74,7 @@ local function worker(user_args)
         widget = wibox.container.arcchart
     }
 
-    local update_graphic = function(_, stdout, _, _, _)
+    local update_graphic = function(widget, stdout, _, _, _)
         local mute = string.match(stdout, "%[(o%D%D?)%]")   -- \[(o\D\D?)\] - [on] or [off]
         local volume = string.match(stdout, "(%d?%d?%d)%%") -- (\d?\d?\d)\%)
         volume = tonumber(string.format("% 3d", volume))
```

**Comment by dapc11** [comment]
This resolved the issue for me as well. Works for volumebar-widget as well.

**Comment by streetturtle** [comment]
WIll apply this some time this week, thanks!!!

**Comment by streetturtle** [comment]
Could you please try https://github.com/streetturtle/awesome-wm-widgets/tree/master/experiments/volume in meanwhile. As I'm about to deprecate volume/arc/bar widgets and replace them by this one. This will remove all the code duplication between these three widgets.

**Comment by dapc11** [comment]
I will give it a try when I have the time. Most likely this weekend. 

Something that has been bothering me using some of the widgets is that they require the arc icon theme, would it be possible to have an option to default to the active system theme?  Or maybe keep the required icons within this repo.

As it is now I clone the repo and hack away the arc reference myself.

**Comment by dapc11** [comment]
@streetturtle experimental volume works like a charm, tried out horizontal_bar and will incorporate that one into my setup from now on. Thanks for the good work.

**Comment by streetturtle** [comment]
Great! I'll collect some more feedback and then will replace current volume widgets with the one from expreriments folder, and will close this issue. Thank you!
