### ISSUE TITLE
Weather widget hourly forecast temp color

### ISSUE THREAD

**Issue by imabuddha** [streetturtle/awesome-wm-widgets#234]
This is a feedback/suggestion, **not** a bug.

I noticed that when it pops up on my system the temperatures in the hourly forecast section are in white not black as shown in the example images. This makes them slightly difficult to read against the yellow sun graph.

As there's no mention of customizing the font colors for the widget I looked in the source code, and I added `foreground="black"` to line 376 of weather.lua like so:

``` lua
markup = '<span foreground="black">' .. string.format('%.0f', hour.temp) .. '°' .. '</span>',
```

This is just my personal preference, and doesn't seem worthy of a pull req., but I thought I'd mention it in case it was an unintentional change.

**Comment by streetturtle** [comment]
I would guess that you're lucky and living in a warm place) 
Initialy the color was black, as on the screenshots, but when I added support for negative temperature, the black was looking bad on the blue background. So I changed it to white:

![image](https://user-images.githubusercontent.com/9363150/105538932-250dbc00-5cc2-11eb-8baa-d4b8c6dd0cb3.png)

The proper fix would be to use black for positive temperatures and white for negative. 
I'll make this fix and will close this ticket.
