### ISSUE TITLE
Battery widget isn't showing up in the bar

### ISSUE THREAD

**Issue by bssb** [streetturtle/awesome-wm-widgets#236]
It did work at one point, when I first configured the battery widget. I'm not sure what changed since then. To debug, I ran awesome within Xephyr and got the following output:

```
021-01-23 19:38:33 W: awesome: a_glib_poll:437: Last main loop iteration took 0.219246 seconds! Increasing limit for this warning to that value.
2021-01-23 19:38:33 E: awesome: Error during a protected call: ...ig/awesome/awesome-wm-widgets/battery-widget/battery.lua:150: attempt to perform arithmetic on a nil value (field '?')
stack traceback:
        ...ig/awesome/awesome-wm-widgets/battery-widget/battery.lua:150: in upvalue 'callback'
        /usr/share/awesome/lib/awful/widget/watch.lua:77: in function </usr/share/awesome/lib/awful/widget/watch.lua:76>
        (...tail calls...)
        /usr/share/awesome/lib/awful/spawn.lua:481: in function </usr/share/awesome/lib/awful/spawn.lua:475>
        [C]: in function 'xpcall'
        /usr/share/awesome/lib/gears/protected_call.lua:36: in function </usr/share/awesome/lib/gears/protected_call.lua:35>
        (...tail calls...)
        /usr/share/awesome/lib/awful/spawn.lua:577: in upvalue 'done'
        /usr/share/awesome/lib/awful/spawn.lua:592: in function </usr/share/awesome/lib/awful/spawn.lua:584>
```

My config: http://ix.io/2N6G

Output of acpi:
```
$ acpi
Battery 0: Full, 100%
Battery 1: Discharging, 0%, rate information unavailable
Battery 2: Full, 100%
```

This is on a ThinkPad X260 with 2 batteries (1 internal and 1 external). I'm not sure why acpi is saying there are 3 batteries. I apologize if this is a misconfiguration on my part. Anyone know what could be wrong? Any tips are greatly appreciated.

edit: running awesome v4.3

**Comment by streetturtle** [comment]
Yep, there is indeed something wrong when laptop has more than one battery. Not sure what would be the best way on handling it. Should it be average of all batteries, or just the first one... I'll think about it and will let you know

**Comment by bssb** [comment]
I've done a little more investigating, and have found that the issue occurs even on laptops that only have one battery. The problem is related to the fact that when my wireless mouse (Logitech MX Master 2S) is powered on and connected, acpi reports an additional battery. This is the battery that I mentioned earlier, where the output of acpi says "rate information unavailable". The path of this device is /sys/class/power_supply/hidpp_battery_2.

If I power on the mouse after starting awesomewm, then the widget is actually able to show all of the batteries (including the Logitech one). However, if the mouse is powered on before starting awesomewm, then the widget crashes and does not start at all.

I think if I dig further into the issue, I may be able to find out exactly why it crashes on startup when the mouse is connected. Maybe it's trying to access a battery property that does not exist for the mouse battery. For now I just wanted to post my findings. The averaging of the batteries may be something to address separately.

**Comment by garywahyudi** [comment]
I recently occur the same problem on this widget i didn't get it work and well after seeing this post I realize i do have a Bluetooth Mouse as well which is the logitech m212 and I hope this will get a fix sooner.

**Comment by bssb** [comment]
This commit fixes the issue I was having. Battery widget now works whether or not my wireless mouse is connected. If you think it looks okay, I can make a PR.

https://github.com/bssb/awesome-wm-widgets/commit/700b4e1f55563ed8d6cc4aed084fe454e67f9534

**Comment by streetturtle** [comment]
That would be great! Please create a PR.
