### ISSUE TITLE
nichosi.png not present

### ISSUE THREAD

**Issue by kopp** [streetturtle/awesome-wm-widgets#24]
For the battery widgets, the `nichosi.png` image is used:

    icon = HOME .. "/.config/awesome/nichosi.png"

This does not seem to be present in my case -- and it is not part of the installation instructions.
I would assume, that this is a bug.

**Comment by streetturtle** [comment]
I was a bit afraid to put it on github due to possible image licencing issues. You can get it here: [vk.com/images/stickers/1933/512.png](https://vk.com/images/stickers/1933/512.png) anyway.  
I will mention it in the README. 

Thanks!

**Comment by streetturtle** [comment]
Fixed by [/f9c00](https://github.com/streetturtle/awesome-wm-widgets/commit/f9c008dc841524efe12647475082c3ec77842121) and [fe0bd2](https://github.com/streetturtle/awesome-wm-widgets/commit/fe0bd2af0811bd1d10b60cb92505c9c3154e31a9)
