### ISSUE TITLE
Logout widget double menu

### ISSUE THREAD

**Issue by randomlylelo** [streetturtle/awesome-wm-widgets#241]
Not sure how to describe this problem but the menu duplicates itself.
![image](https://user-images.githubusercontent.com/38267386/108114555-f38cd400-7066-11eb-9692-e9e7e673b03b.png)

I'm running on Arch Linux,  Awesome WM v4.3.
I didn't try to customize it, just followed the installation instructions but that is what it pops up.

I took a look at the code but I am a complete Lua newbie so I wasn't able to figure out anything but I managed to get this: 
![image](https://user-images.githubusercontent.com/38267386/108115022-8f1e4480-7067-11eb-9a45-a14b010dfe8f.png)
not sure how much that helps tho.

I also get this error once I click out of the menu (every once in a while, not sure what I do to make it happen): 
![image](https://user-images.githubusercontent.com/38267386/108114977-80379200-7067-11eb-83c0-5a6add2a49cf.png)

Thanks! Love your work btw.
Let me know if you need any additional info.

**Comment by streetturtle** [comment]
Hi! Thanks for raising the issue!
Do you have two screens?

**Comment by streetturtle** [comment]
Can you try the latest master, please - I think I've found the problem and fixed it.

**Comment by randomlylelo** [comment]
> Hi! Thanks for raising the issue!
> Do you have two screens?

Yes! I have a dual monitor setup.

Sorry for the late response but yeah the current master works!
