### ISSUE TITLE
battery widget isn't vertically centered

### ISSUE THREAD

**Issue by flexagoon** [streetturtle/awesome-wm-widgets#243]
basically what the title says.
![image](https://user-images.githubusercontent.com/66178592/109140941-0c774280-7755-11eb-8ff1-64d170e08cf3.png)
As you can see, all widgets are nicely aligned, but the battery one just sticks to the top. How do I change this behavior?

**Comment by streetturtle** [comment]
Hi! Could you please try the latest master and let me know - it should be aligned now.

**Comment by bssb** [comment]
I just wanted to say that the icon is now properly aligned for me, after pulling the latest commit. Thank you for the fix!

**Comment by flexagoon** [comment]
It is working. However, some other widgets are still not centered. I managed to patch them myself, but it would be nice if it was in that align mode by default.
