### ISSUE TITLE
all logout menu entries are duplicated on dual monitor setup!

### ISSUE THREAD

**Issue by kgavionics** [streetturtle/awesome-wm-widgets#244]
Hello
I was using the Logout menu widget on a single monitor and I didn't have any problem.Recently, I added another monitor all the logout menu widget (logout, lock, reboot...) are duplicated!see link bellow

Is there a chance to fix this issue please!

**Comment by streetturtle** [comment]
Hi! Can you please try the latest master, and let me know - I think I've fixed it just recently.

**Comment by kgavionics** [comment]
Thank you! the widget included in the latest master fixed the problem!
