### ISSUE TITLE
calendar-widget

### ISSUE THREAD

**Issue by CoolVARG** [streetturtle/awesome-wm-widgets#245]
the config does not break, but it also does not work out the widget.
here is an excerpt:

-- MyTextclock
mytextclock = awful.widget.textclock("%a %d %b, %H:%M ", 1)

-- Calendar
local cw = calendar_widget({
    theme = 'dark',
    placement = 'top_right',
    radius = 8,
})
mytextclock:connect_signal("button::press", 
    function(_, _, _, button)
        if button == 1 then cw.toggle() end
    end)

**Comment by streetturtle** [comment]
The code looks ok and works for me, do you have any error message in the logs?
