### ISSUE TITLE
Local characters not supported (Spotify widget)

### ISSUE THREAD

**Issue by real-esekyl** [streetturtle/awesome-wm-widgets#247]
I don't know if this is true for every widget:
the Spotify widget does not display the correct non-English characters.
Example: Instead of Ä it shows \xc3\x84.

I don't know much lua, so I just used a gsub chain which substitutes every important German umlaut. I can imagine, this is also a problem with Spanish, French and other characters as well. 
```

        local amp = string.gsub(stdout, "&", '&amp;')
        local Auml = string.gsub(amp, "\\xc3\\x84", '&#196;')
        local auml = string.gsub(Auml, "\\xc3\\xa4", '&#228;')
        local Ouml = string.gsub(auml, "\\xc3\\x96", '&#214;')
        local ouml = string.gsub(Ouml, "\\xc3\\xb6", '&#246;')
        local Uuml = string.gsub(ouml, "\\xc3\\x9c", '&#220;')
        local uuml = string.gsub(Uuml, "\\xc3\\xbc", '&#252;')
        local escaped = string.gsub(uuml, "\\xc3\\x9f", '&#223;')

```
There is most probably an easier/cleaner solution for formatting the string.

**Comment by real-esekyl** [comment]
Closing this due to a wrong locale setting on my side...

**Comment by streetturtle** [comment]
Hi! Can you please share some details?

**Comment by real-esekyl** [comment]
My locales were set to "C" somehow after reinstalling Arch. After I set locale correctly, it now displays all special characters automatically correctly.
