### ISSUE TITLE
volume-widgets produces attempt to index a nil value (local 'user_args')

### ISSUE THREAD

**Issue by floli** [streetturtle/awesome-wm-widgets#248]
Hello,

using latest git master for both awesome-wm-widgets and awesome ifself (the latter by means of https://aur.archlinux.org/packages/awesome-git/), I try to add the volume-widget:
```
local volume_widget = require("awesome-wm-widgets.volume-widget.volume")
```
and later
```
volume_widget()
```
inside a awful.wibar. Other widgets in the same bar and from this repo are working fine, but the `volume_widget()` produces
```
error while running function!
stack traceback:
        ...nfig/awesome/awesome-wm-widgets/volume-widget/volume.lua:170: in function <...nfig/awesome/awesome-wm-widgets/volume-widget/volume.lua:162>
        (...tail calls...)
        /home/florian/.config/awesome/rc.lua:705: in main chunk
error: ...nfig/awesome/awesome-wm-widgets/volume-widget/volume.lua:170: attempt to index a nil value (local 'user_args')
```
Any idea? Is my git version of awesome not a good idea?

Thanks!

**Comment by streetturtle** [comment]
Thank you for there issue! There was a bug - if no parameters got passed, it fails. I've just fixed it. Should be ok now :+1:

**Comment by floli** [comment]
Awesome, I can happily confirm the fix works!
