### ISSUE TITLE
Weather widget margins are cutting off the text

### ISSUE THREAD

**Issue by bssb** [streetturtle/awesome-wm-widgets#258]
I recently updated my copy of the repository and noticed that the top and bottom of my weather widget were now being cut off, as shown here:
![wibar1](https://user-images.githubusercontent.com/7004951/116163828-816be780-a6c6-11eb-874c-447fb61c48dc.jpg)

I believe it is this commit that caused the change: 
https://github.com/streetturtle/awesome-wm-widgets/commit/0054af2de3da8fb0cc0d2deb9738ceefc97ea5e7

If I change margins from 4 to 0, like so:
https://github.com/bssb/awesome-wm-widgets/commit/2aa99df043fc05cc54d1b72d9f92ea6b9d335c6d

then the top and bottom are back to the way it was before, not being cut off:
![widget2](https://user-images.githubusercontent.com/7004951/116164105-1ff84880-a6c7-11eb-9bed-1054e9209aa3.jpg)

I am using DejaVu Sans 12 by the way. Do the margins need to be 4 for some other reason, or could we change it to 0?

**Comment by streetturtle** [comment]
There is a bug - margins intended to be on the left and right sides of the widget. I will fix it and will let you know.

Thanks!

**Comment by bssb** [comment]
Thank you! I really appreciate it.

**Comment by streetturtle** [comment]
Should be ok now, feel free to reopen if the fix did't help.

**Comment by bssb** [comment]
That fixed it. Thanks.
