### ISSUE TITLE
Spotify Widget doesn't work

### ISSUE THREAD

**Issue by quantumfate** [streetturtle/awesome-wm-widgets#263]
When I type "sp help" I get the help notice printed. So the script is properly installed.

But when I type any other command (like "sp status"), I get the following error message: 

```
Failed to open connection to "session" message bus: Failed to connect to socket /tmp/dbus-R0dDoXVhBi: Connection refused
```

I am not sure if that's actually the issue why the widget is not working for me but I believe it's worth noticing that the script from the spotify-CLI includes the following lines

```
# To get SP_ID and SP_SECRET register at
# https://beta.developer.spotify.com/documentation/general/guides/app-settings/
SP_ID="<yout id>"
SP_SECRET="<your secret>"
```

So I thought maybe something is missing there.

I also wanna mention that I am using Manjaro and I tried several spotify versions from the arch repo

**Comment by streetturtle** [comment]
Hi! Looks like it's a dbus-related issue. I'll try to investigate more and will let you know.

**Comment by quantumfate** [comment]
> Hi! Looks like it's a dbus-related issue. I'll try to investigate more and will let you know.

Hey! Thanks. Let me know if I can provide further information for you to investigate.

**Comment by quantumfate** [comment]
```
dbus-launch --exit-with-session spotify
```
Is giving me a slightly different error now

```
/opt/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/spotify/spotify)
/opt/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/spotify/spotify)
/proc/self/exe: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe
```

Plus using "sp" now gives me:

```
Failed to open connection to "session" message bus: Failed to connect to socket /tmp/dbus-YTo1MZjDke: Connection refused
```

**Comment by quantumfate** [comment]
Following the comments in [this](https://gist.github.com/wandernauta/6800547) gist ... It seems like that Spotify on arch doesn't register itself automatically to the dbus. But I just can't figure out how to fix that.

**Comment by quantumfate** [comment]
I get the same behaviour with [mpris-ctl](https://aur.archlinux.org/packages/mpris-ctl/) starting to think that it is an OS related issue but I have trouble figuring out what is goint on.

**Comment by quantumfate** [comment]
So I firgured out why it is not working for me. It doesn only seem to work with the spotify version installed from snap store.
The sp script mentioned as a requirement is looking for a DBUS_SESSION_BUS_ADRESS. 
```
SPOTIFY_PID="$(pidof -s spotify)"

if [[ -z "$SPOTIFY_PID" ]]; then
  echo "Error: Spotify is not running."
  exit 1
fi

QUERY_ENVIRON="$(cat /proc/${SPOTIFY_PID}/environ | tr '\0' '\n' | grep "DBUS_SESSION_BUS_ADDRESS" | cut -d "=" -f 2-)"
if [[ "${QUERY_ENVIRON}" != "" ]]; then
  export DBUS_SESSION_BUS_ADDRESS="${QUERY_ENVIRON}"
fi
```

recreating this 

```
➜ pidof -s spotify
170247

cat /proc/170247/environ | tr '\0' '\n' | grep "DBUS_SESSION_BUS_ADDRESS" | cut -d "=" -f 2-
# No output

```

This supposedly results into the following error when using sp

```
➜ sp play
Failed to open connection to "session" message bus: Failed to connect to socket /tmp/dbus-3UXBoNKdFB: Connection refused

~
➜ sp status
Failed to open connection to "session" message bus: Failed to connect to socket /tmp/dbus-3UXBoNKdFB: Connection refused
```

**Comment by quantumfate** [comment]
using the terminal based spotify client [spotify_player](https://aur.archlinux.org/packages/spotify-player/) does provide a DBUS_SESSION_BUS_ADDRESS but the issue persists.

```
➜ pidof -s spotify_player
1426409

~
➜ cat /proc/1426409/environ | tr '\0' '\n' | grep "DBUS_SESSION_BUS_ADDRESS" | cut -d "=" -f 2-
unix:abstract=/tmp/dbus-3UXBoNKdFB,guid=5bf152e3e90edec1a01958b561a494fc

~
➜ export DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-3UXBoNKdFB,guid=5bf152e3e90edec1a01958b561a494fc

~
➜ sp status
Failed to open connection to "session" message bus: Failed to connect to socket /tmp/dbus-3UXBoNKdFB: Connection refused
```

**Comment by quantumfate** [comment]
It works now.
