### ISSUE TITLE
Two icons for volume and battery widgets.

### ISSUE THREAD

**Issue by cloud-009** [streetturtle/awesome-wm-widgets#268]
I'm using default for volume but the 'icon_and_text' appears on it's own.Also same with the battery-widget, two icons appear.

**Comment by streetturtle** [comment]
Could you please provide a screenshot?

**Comment by cloud-009** [comment]
When I call volume_widget(), and then again I do volume_widget ({ type = 'arc' }), it shows two icon. But if I just call it once and define the type of widget it works perfect. 
Sorry to bother you :)
--This is default --
 volume_widget(),
               volume_widget{
            widget_type = 'arc'
        },

--Now--
volume_widget{
widget_type = 'arc'
},
