### ISSUE TITLE
Update minimum awesomewm version in docs for certain widgets

### ISSUE THREAD

**Issue by mfanourakis** [streetturtle/awesome-wm-widgets#270]
If you include widgets that make use of the function `awful.popup` in `rc.lua` for awesomewm v4.2 and below you will get the following error. 
> attempt to call a nil value (field 'popup')

Ex. ram_widget, cpu_widget .

awful.popup was implemented in awesomewm v4.3+ , please update the readmes of the relevant widgets appropriately.

**Comment by streetturtle** [comment]
I realized that most of the widgets are using `awful.popup`, so I decided to add this requirement in the main README.
