### ISSUE TITLE
Customizing the volume control step

### ISSUE THREAD

**Issue by TD-Sky** [streetturtle/awesome-wm-widgets#284]
Is there any parameter of `volume_widget()` that stand for  volume control step, which is similar to the brightness-widget's ?

If there is no such feature, are you going to add one ? It's very useful :)

**Comment by TD-Sky** [comment]
I implement this as it is not so hard.

**Comment by streetturtle** [comment]
Could you create a PR? If not, it's not a problem, I'll add it this week.
