### ISSUE TITLE
Spotify Widget (question)

### ISSUE THREAD

**Issue by raven2cz** [streetturtle/awesome-wm-widgets#311]
I'm using spotify widget in the default awesomewm panel.
example:
```lua
    s.mywibox.widget = {
      layout = wibox.layout.align.horizontal,
      { -- Left widgets
        layout = wibox.layout.fixed.horizontal,
        mylauncher,
        separator,
        s.mytaglist,
        separator,
        s.mypromptbox,
      },
      s.mytasklist, -- Middle widget
      { -- Right widgets
        layout = wibox.layout.fixed.horizontal,
        separator,
        spotifyWibox,
        separator,
        todo_widget(),
        separator,
        wibox.widget.systray(),
        separator,
        keyboardWibox,
        fsWibox,
        memWibox,
        cpuWibox,
        tempWibox,
        alsaWibox,
        netWibox,
        weatherWibox,
        clockWibox,
        s.mylayoutbox,
      },
```

The configuration of spotify widget is
```lua
-- Spotify widget
local spotifyWibox = spotify_widget({
  font = theme.font,
  max_length = 500,
  play_icon = '/usr/share/icons/Papirus-Light/24x24/categories/spotify.svg',
  pause_icon = '/usr/share/icons/Papirus-Dark/24x24/panel/spotify-indicator.svg'
})
```

But the widget size is still around just 150px, the each song names is cut and have to rotate. I have much more space in the panel.

Is there some way how to force minimal size, or add preference to extend the spotify size. Or maybe create some wibox container which extends the spotify included cmp, but I don't know if the spotify will be correctly resized.

**Comment by streetturtle** [comment]
Hi! Could you please share a screenshot?

**Comment by raven2cz** [comment]
![spotify-short-width](https://user-images.githubusercontent.com/20504243/140641755-aa537133-a57f-4228-8b56-1c738041699e.jpg)

**Comment by davidk55** [comment]
Hello, I just have the same problem right now. I also tried `-1` and big numbers like `1000` for the `max_length`, but it do not apply and still shows only part of the name. Would be cool if you can give some context in how you fixed it if you did @raven2cz

**Comment by raven2cz** [comment]
Hi,

https://github.com/streetturtle/awesome-wm-widgets/issues/328

Included zip file. There are all important changes for spotify.lua and todo.lua. The issue is not still processed. It is not just about light theme. I extends the spotify length and much more. It needs better external configuration of these components. But it is not done. And it is a reason why I don't created PR. But it can help you, you can create your patch or improve it and create PR.

**Comment by davidk55** [comment]
Just tried your fix and it works perfectly, thanks
