### ISSUE TITLE
Website out of date

### ISSUE THREAD

**Issue by brooksvb** [streetturtle/awesome-wm-widgets#330]
The website http://pavelmakhov.com/awesome-wm-widgets/ is out of date, which was causing me issues until I realized the documentation I was reading had an outdated parameter name (volume widget type parameter is now widget_type). It also seems to be listing some widgets that are no longer there: volume_bar volume_arc.

I think it would be helpful to others to prevent them from going down the same path I did, not even realizing I was looking at outdated docs until I had tracked down the parameter name in the source code. It seems the doc website is generated from the READMEs, so hopefully that's a quick fix.

**Comment by streetturtle** [comment]
Thank you for raising the issue! And sorry for your wasted time.
I have setup a new gh-action, which updates the site when there are any changes to README.md files (previously it was done manually), so the site should be always up date. However, there are still few issues, like missing images. I will address those later.
