### ISSUE TITLE
brightness_widget: incorrect brightnessctl command for getting current brightness level

### ISSUE THREAD

**Issue by FerrielMelarpis** [streetturtle/awesome-wm-widgets#399]
Hi there, awesomewm beginner here.
First of, thanks for this awesome project.

#### Description
When setting the brightness_widget settings to 
```lua
brightness_widget({
  type = "icon_and_text",
  program = "brightnessctl",
})
```
the text displayed is not a percentage value but actual brightness value.
In my case it shows `14543` for e.g. and the max brightness value `19393`.

#### Possible solution
To get the actual percentage, I think we can use `brightnessctl -m | cut -d, f4 | tr -d %`.

Happy to create a PR to fix this and get myself familiar with awesomewm.

**Comment by jelleh** [comment]
#brightnessctl --version
0.5

#brightnessctl          
Device 'intel_backlight' of class 'backlight':
	Current brightness: 496 (100%)
	Max brightness: 496

#brightnessctl max 
496

#brightnessctl get
246

**Quick fix**
i call a little script
```
#!/bin/sh
brightnessctl |awk '{if ($1 == "Current") {gsub("(\\(|\\)|%)",""); print $4} }'

```

**Possible solution**
I think you have to calculate the percentage with (brightnessctl get/brightnessctl max)x100
