### ISSUE TITLE
Change color font on the spotify-widget Widget

### ISSUE THREAD

**Issue by Wallsified** [streetturtle/awesome-wm-widgets#406]
Hi. How can I change the color of the text on the widget? 
Im trying to make it orange so it matches with my dotfiles but I can't figure out if I can do that.

**Comment by streetturtle** [comment]
Hi! Unfortunately, it's not supported. However, you can add it by wrapping text in <span> tag, something like this:

```
self:get_children_by_id('artistw')[1]:set_markup("<span foreground=#FFA500 >" .. artist_to_display .. "</span>")
```

on lines [97](https://github.com/streetturtle/awesome-wm-widgets/blob/master/spotify-widget/spotify.lua#L97) and [101](https://github.com/streetturtle/awesome-wm-widgets/blob/master/spotify-widget/spotify.lua#L101).

**Comment by streetturtle** [comment]
Another way could be to change the `beautiful.fg_normal` variable in theme.lua.

**Comment by Wallsified** [comment]
The `beautiful.fg_normal` tweak did the trick. Thanks!
