### ISSUE TITLE
apt widget not working because icon does not show in bar

### ISSUE THREAD

**Issue by radiodee1** [streetturtle/awesome-wm-widgets#430]
Hi,

I've been using the apt-widget. It has gone back and forth between working and not working. Presently the version on the repository does not work. The icon for the widget does not appear. I changed line 362 to read ' return apt_widget ' when it formerly read ' return apt_widget_button '. Now the icon shows up on the bar. I don't know if this is the only change needed to make the widget work.

```
diff --git a/apt-widget/apt-widget.lua b/apt-widget/apt-widget.lua
index a28a42c..2a4c683 100644
--- a/apt-widget/apt-widget.lua
+++ b/apt-widget/apt-widget.lua
@@ -359,7 +359,7 @@ local function worker(user_args)
                end
        end)
 
-       return apt_widget_button
+       return apt_widget -- apt_widget_button
 end
 
 return setmetatable(apt_widget, {
```

**Comment by radiodee1** [comment]
Hi. The return statement has changed since the widget was originally written. Maybe you could look at one of the early commits? Somewhere along the line `return apt_widget` was changed to `return apt_widget_button`. I don't know exactly how or why. The unfortunate thing is that you have to be running a debian based system to test this. I'm using Ubuntu 23.10, but I know that's not the most popular distro. I hope I'm being clear.

**Comment by streetturtle** [comment]
@radiodee1, could you please check if it works now?

**Comment by radiodee1** [comment]
Hi. It seems to work. The icon does show up in the bar. Thanks.
