### ISSUE TITLE
volume-widget issue: volume-widget/volume.lua:243: bad argument #2 to 'format' (number expected, got nil)

### ISSUE THREAD

**Issue by raisinbl** [streetturtle/awesome-wm-widgets#449]
I follow default installation for volume widget and got this
```bash
024-07-21 13:03:58 E: awesome: Error during a protected call: ...nfig/awesome/awesome-wm-widgets/volume-widget/volume.lua:243: bad argument #2 to 'format' (number expected, got nil)
stack traceback:
	[C]: in function 'string.format'
	...nfig/awesome/awesome-wm-widgets/volume-widget/volume.lua:243: in upvalue 'callback'
	/usr/share/awesome/lib/awful/widget/watch.lua:77: in function </usr/share/awesome/lib/awful/widget/watch.lua:76>
	(...tail calls...)
	/usr/share/awesome/lib/awful/spawn.lua:481: in function </usr/share/awesome/lib/awful/spawn.lua:475>
	[C]: in function 'xpcall'
	/usr/share/awesome/lib/gears/protected_call.lua:36: in function </usr/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
	/usr/share/awesome/lib/awful/spawn.lua:577: in upvalue 'done'
	/usr/share/awesome/lib/awful/spawn.lua:592: in function </usr/share/awesome/lib/awful/spawn.lua:584>
```

**Comment by huyld** [comment]
I had this issue as well.
From the [README](https://github.com/streetturtle/awesome-wm-widgets/blob/68ddbd9812979f1862ebd07f1bf5aa409952e935/volume-widget/README.md?plain=1#L39) file:
> Note that the widget uses following command to get the current volume: `amixer -c 1 -D pulse sget Master`, so please make sure that it works for you

In my case the card should be `0` instead of `1`. Hence I need to pass the correct card: 
```lua
        volume_widget{
            widget_type = 'arc',
            card = 0
        },
```

**Comment by utix** [comment]
imho default be 0 not 1, majority of user has one card not 2

**Comment by Luka5W** [comment]
Good question. I have no clue.

I think I was just looking at the example section in the amixer(1) man page and thought they were counting from 1 instead of 0, or using 1 as the default for some reason. maybe lua has traumatized me a bit ^^

#456 seems right.
