### ISSUE TITLE
battery and battery arc do not work on my kali based laptop

### ISSUE THREAD

**Issue by bda65** [streetturtle/awesome-wm-widgets#62]
Hi,
I'm running Awesome WM 4.2 under kali with 4.18.0-kali3-amd64 kernel (last update). Laptop is Alienware 13R3 OLED.

battery-widget report:
`2018-12-19 15:07:54 E: Error during a protected call: ...ig/awesome/awesome-wm-widgets/battery-widget/battery.lua:101: attempt to perform arithmetic on a nil value (field '?')
stack traceback:
        ...ig/awesome/awesome-wm-widgets/battery-widget/battery.lua:101: in upvalue 'callback'
        /usr/share/awesome/lib/awful/widget/watch.lua:77: in function </usr/share/awesome/lib/awful/widget/watch.lua:76>
        (...tail calls...)
        /usr/share/awesome/lib/awful/spawn.lua:308: in function </usr/share/awesome/lib/awful/spawn.lua:302>
        [C]: in function 'xpcall'
        /usr/share/awesome/lib/gears/protected_call.lua:36: in function </usr/share/awesome/lib/gears/protected_call.lua:35>
        (...tail calls...)
        /usr/share/awesome/lib/awful/spawn.lua:403: in upvalue 'done'
        /usr/share/awesome/lib/awful/spawn.lua:418: in function </usr/share/awesome/lib/awful/spawn.lua:410>`

Same with batteryarc-widget but with different line number.

**acpi report:**
Battery 0: Discharging, 0%, rate information unavailable
Battery 1: Full, 100%

**acpi -i report:**
Battery 0: Discharging, 0%, rate information unavailable
Battery 1: Full, 100%
Battery 1: design capacity 5000 mAh, last full capacity 4340 mAh = 86%

**Comment by streetturtle** [comment]
Hi! I pushed possible fix for this issue yesterday and it works for one of my setups - the problem was in this line: `Battery 0: Discharging, 0%, rate information unavailable`. Can you try batteryarc and let me know if it works.

**Comment by bda65** [comment]
Hi, it work :)
Thank you <3
