### ISSUE TITLE
Spotify-shell "Next not working 

### ISSUE THREAD

**Issue by batmanm0b1E** [streetturtle/awesome-wm-widgets#64]
Hi i got spotify-shell working everything works but Pause doesn't work any help on fixing it. It just goes to next track when i hit Pause

**Comment by streetturtle** [comment]
@batmanm0b1E Hi, thanks for raising the issue!
What happens if you run ’sp pause’ in terminal?

**Comment by batmanm0b1E** [comment]
ok thats my fault. its working now. I think i spelled it wrong goof mistake on my part. I have another question when i'm on and album same one and i hit next it doesn't go to the next track

**Comment by streetturtle** [comment]
Hm, can you play next from Spotify client - if you click next there? Or if you run `sp next` from terminal?

**Comment by batmanm0b1E** [comment]
if i click next with spotify client it stays on that album i'm on. But if i do it with sp next jumps off same with spotify shell

**Comment by batmanm0b1E** [comment]
WOW you fixed it already!!! its like magic seems its working now right. Too funny

**Comment by batmanm0b1E** [comment]
As soon as i hit prev back and then next in sp it started working right. Your the Magic turtle Mikey

**Comment by streetturtle** [comment]
I guess I can close it :tada:
