### ISSUE TITLE
My layout is faulty

### ISSUE THREAD

**Issue by matthiasbe** [streetturtle/awesome-wm-widgets#66]
Hi,
First of all thank for sharing this code publicly :)
I have trouble using your widgets on Awesome WM.

I have cloned the repo in `.config/awesome/`

This is my config file `.config/awesome/rc.lua` :

```lua
    local brightness_w = require("awesome-wm-widgets.brightness-widget.brightness")
    local batteryarc_widget = require("awesome-wm-widgets.batteryarc-widget.batteryarc")
    local volumearc_widget = require("awesome-wm-widgets.volumearc-widget.volumearc")

    -- Add widgets to the wibox
    s.mywibox:setup {
        layout = wibox.layout.align.horizontal,
        { -- Left widgets
            layout = wibox.layout.fixed.horizontal,
            mylauncher,
            s.mytaglist,
            s.mypromptbox,
        },
        s.mytasklist, -- Middle widget
        { -- Right widgets
            layout = wibox.layout.fixed.horizontal,
            wibox.widget.systray(),
            volumearc_widget,
            brightness_w,
            batteryarc_widget,
            mytextclock,
            s.mylayoutbox,
        },
    }
```

And the result is this

![image](https://user-images.githubusercontent.com/9254232/51684097-9dfeae00-1feb-11e9-9842-9e1ce4011771.png)

Do you have any idea of something I did wrong ?

I'm using debian testing and awesome 4.2.

Thank you for your help ;)
Matthias

**Comment by streetturtle** [comment]
Thank you for trying to use them!
Let's go one by one:
 - VolumeArc
    Widget uses following command to control the volume:
    ```lua
    local GET_VOLUME_CMD = 'amixer -D pulse sget Master'
    local INC_VOLUME_CMD = 'amixer -D pulse sset Master 5%+'
    local DEC_VOLUME_CMD = 'amixer -D pulse sset Master 5%-'
    local TOG_VOLUME_CMD = 'amixer -D pulse sset Master toggle'
    ```
    Try to run them in terminal and see if volume changes - maybe the problem is that you don't have alsamixer installed.
 - Brightness
    Same thing, try these commands in terminal first:
    ```lua
    local GET_BRIGHTNESS_CMD = "light -G"   -- "xbacklight -get"
    local INC_BRIGHTNESS_CMD = "light -A 1" -- "xbacklight -inc 5"
    local DEC_BRIGHTNESS_CMD = "light -U 1" -- "xbacklight -dec 5"
    ```

 - BatteryArc - the problem is in font size, try to decrease it in [here](https://github.com/streetturtle/awesome-wm-widgets/blob/master/batteryarc-widget/batteryarc.lua#L12)

Please let me know it something from above helped. And sorry for misleading docs.

**Comment by streetturtle** [comment]
Regarding the missing text in batterarc widget there was a problem indeed - the value had a decimal part, so if was overflowing the box, this [commit](https://github.com/streetturtle/awesome-wm-widgets/commit/70fd5a38b0fcd9d1399d3d978f05d9964abb812c) fix it. Also make sure that you have Play font installed. Please let me know if it helped.

**Comment by matthiasbe** [comment]
Hello,
Thank you for your quick answers.

I guess I was expecting to get the exact same layout as you showed in screenshots, and I was preoccupied because I did not get the same nice associated text (brightness percentage for example) and gap between icons.

Deducing from your answers, I guess those layout settings have to be set in addition to your widget.

Bye
Matthias

**Comment by matthiasbe** [comment]
Pulling changes and installing fonts solved the problem, thanks !

**Comment by streetturtle** [comment]
Inside the brightness widget code you just need to replace light commands with the ones you use.
