### ISSUE TITLE
Brightness widget, does not read value correctly

### ISSUE THREAD

**Issue by l1k3ab0t** [streetturtle/awesome-wm-widgets#77]
The brightness widget matches only the first 2 digits, therefore 100% Brightness is shown as 0% on the widget (if `light -G` returns `100.00`).

From [brightnessarc.lua](https://github.com/streetturtle/awesome-wm-widgets/blob/master/brightnessarc-widget/brightnessarc.lua):
` local brightness_level = string.match(stdout, "(%d?%d?)")`

Modifying the line above to 
` local brightness_level = string.match(stdout, "(%d?%d?%d?)")` 
fixes the issue.

**Comment by streetturtle** [comment]
Good catch! Thanks! :+1:
