### ISSUE TITLE
mdparc_widget is not a widget. 

### ISSUE THREAD

**Issue by kub1x** [streetturtle/awesome-wm-widgets#78]
I tried to add the `mpdarc_widget` as written in README and got following error. 

![image](https://user-images.githubusercontent.com/1833840/55800781-c8351780-5ad4-11e9-8308-4bdea82bc520.png)

I [looked the error up](https://github.com/awesomeWM/awesome/blob/master/lib/wibox/widget/base.lua#L720) and it seems to be checking for `is_widget` property which is not there. 

I tried to dump the variable and it is there just as returned by the module.. the table of two sub-widgets and layout. Perhaps the returned object should also be created using `wibox.widget`? Would try and PR it, but I don't know how to use `wibox` to "merge two widgets together using layout". 

I'm on `x11-wm/awesome-4.2-r2`

**Comment by kub1x** [comment]
Ok. Maybe like this: https://github.com/streetturtle/awesome-wm-widgets/pull/79 ;)

**Comment by streetturtle** [comment]
Should be resolved now
