### ISSUE TITLE
Battery Arc not updating anymore on Awesome 4.3

### ISSUE THREAD

**Issue by teranex** [streetturtle/awesome-wm-widgets#80]
I upgraded to Awesome 4.3. Now the battery arc is not updating anymore. Only when Awesome starts (or restarts) the widget is drawn correctly, but then keeps showing the state of the battery from the moment Awesome was started. Under Awesome 4.2 my config worked correctly. I tested the latest version of awesome-wm-widget (master branch), but this doesn't seem to make a difference.

I think this is caused by the following error:

```
2019-04-23 14:15:52 E: awesome: Error during a protected call: /usr/share/awesome/lib/wibox/container/arcchart.lua:111: attempt to perform arithmetic on a function value (local 'v')                          
stack traceback:
	/usr/share/awesome/lib/wibox/container/arcchart.lua:111: in function 'awesome-wm-widgets.batteryarc-widget.batteryarc.after_draw_children'
	[C]: in function 'xpcall'
	/usr/share/awesome/lib/gears/protected_call.lua:36: in function </usr/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
	/usr/share/awesome/lib/wibox/hierarchy.lua:323: in local 'call'
	/usr/share/awesome/lib/wibox/hierarchy.lua:348: in function 'wibox.hierarchy.draw'
	/usr/share/awesome/lib/wibox/hierarchy.lua:345: in function 'wibox.hierarchy.draw'
	/usr/share/awesome/lib/wibox/hierarchy.lua:345: in function 'wibox.hierarchy.draw'
	/usr/share/awesome/lib/wibox/hierarchy.lua:345: in function 'wibox.hierarchy.draw'
	/usr/share/awesome/lib/wibox/hierarchy.lua:345: in function 'wibox.hierarchy.draw'
	/usr/share/awesome/lib/wibox/drawable.lua:160: in upvalue 'do_redraw'
	/usr/share/awesome/lib/wibox/drawable.lua:390: in function </usr/share/awesome/lib/wibox/drawable.lua:388>
	[C]: in function 'xpcall'
	/usr/share/awesome/lib/gears/protected_call.lua:36: in function </usr/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
	/usr/share/awesome/lib/gears/timer.lua:231: in function </usr/share/awesome/lib/gears/timer.lua:229>
```

My config is available here: https://github.com/teranex/awesome-config/tree/awesome-4.0

**Comment by streetturtle** [comment]
Thanks for raising an issue :+1:  I am on 4.2 now and haven't tested on 4.3 yet. AFAIR there are some breaking changes with `awful.spawn`. I'll upgrade my awesome this week and will fix the issues. I'll post here when I'm done.

**Comment by streetturtle** [comment]
I was wrong, there are no breaking changes in 4.3 for `awful.spawn`. And I just upgraded to 4.3 and batteryarc works as expected, at least updates the arcchart. Could you please try master again.  
BTW, where did you get the error log from?

**Comment by teranex** [comment]
I'm now using master (commit 54924ef), but the result is still the same.
Looking in the logs I found another error which seems to be real culprit:

```
2019-04-25 12:21:10 E: awesome: Error during a protected call: ...some/awesome-wm-widgets/batteryarc-widget/batteryarc.lua:103: bad argument #2 to 'format' (number has no integer representation)
stack traceback:
	[C]: in function 'string.format'
	...some/awesome-wm-widgets/batteryarc-widget/batteryarc.lua:103: in upvalue 'callback'
	/usr/share/awesome/lib/awful/widget/watch.lua:77: in function </usr/share/awesome/lib/awful/widget/watch.lua:76>
	(...tail calls...)
	/usr/share/awesome/lib/awful/spawn.lua:481: in function </usr/share/awesome/lib/awful/spawn.lua:475>
	[C]: in function 'xpcall'
	/usr/share/awesome/lib/gears/protected_call.lua:36: in function </usr/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
	/usr/share/awesome/lib/awful/spawn.lua:577: in upvalue 'done'
	/usr/share/awesome/lib/awful/spawn.lua:592: in function </usr/share/awesome/lib/awful/spawn.lua:584>
```

In batteryarc.lua if I change line 103 to:

```lua
                    -- or string.format('%d', charge)
                    or charge
```

The widget works, although without a textual percentage (it always shows three dots as the text).
With the original line, the arc-ring is also always white, while with the change it shows the correct colors (usually a green ring and yellow when below 30% (?))*. 

I did upgrade from Ubuntu 18.04 to 19.04 (which brought Awesome 4.3 with it), but I don't think this changed anything in the `acpi -i` output. As far as I see the regexes all still match the expected output. I do have a Bluetooth keyboard which has no (useful) battery info available, but that should be filtered out as well. When I disable my Bluetooth keyboad it does not make any difference for the widget.

Output of `acpi -i`:
```
Battery 0: Charging, 55%, 00:37:31 until charged
Battery 0: design capacity 3598 mAh, last full capacity 2919 mAh = 81%
Battery 1: Discharging, 0%, rate information unavailable
Battery 2: Unknown, 5%
Battery 2: design capacity 2097 mAh, last full capacity 1516 mAh = 72%
```

I obtained the logs by running awesome from bash: `awesome -r &`

**Comment by teranex** [comment]
Adding a debug line before line 101 shows me that `charge` is a float:

```
            print("----- Charge: " .. charge)
```
```
----- Charge: 46.099518459069
```

changing line 103 to:
```
                    or string.format('%2.0f', charge)
```
seems to fix the issue

**Comment by syhe** [comment]
@teranex It looks like the first error you described was caused by the leftover `set_value` function in the widget declaration. When I removed it, the error disappeared.

**Comment by dyfrgi** [comment]
Should this issue be closed since the issue was in configuration, not in this repo?

**Comment by streetturtle** [comment]
@dyfrgi yep, you right, thanks!
