### ISSUE TITLE
[BUG] Weather widget uses a blocking HTTP call

### ISSUE THREAD

**Issue by webknjaz** [streetturtle/awesome-wm-widgets#81]
This creates problems and freezes Awesome whenever the Internet connection is unstable.

The workaround is to asynchronously spawn curl subprocess: https://github.com/vicious-widgets/vicious/blob/9cf9e99/widgets/weather_all.lua#L95

**Comment by streetturtle** [comment]
That's a good idea to spawn a curl instead of using a lua's http lib. I'll create another version of the widget with curl. Thanks!
