### ISSUE TITLE
Problem with ssl.https dependency

### ISSUE THREAD

**Issue by vevais** [streetturtle/awesome-wm-widgets#90]
I get the following error after following your instructions and trying to implement the translation widget. What am I missing?
![2019-08-08-004201_1366x768_scrot](https://user-images.githubusercontent.com/11073216/62662893-e2451080-b975-11e9-9574-5ef0b8ca9cdc.png)

My Lua-version is 5.3.5 and I use awesome v4.3

**Comment by vevais** [comment]
I got it to work after installing luasec and luajson. However I can't seem to find where to put the API key in translate.lua, as the is no API_KEY variable as mentioned in the wiki.

**Comment by streetturtle** [comment]
Hi, you should get it from here: https://translate.yandex.com/developers/keys and then either use it in secrets.lua or paste directly in the widget. 
I'm currently working on the  improvement which will allow to pass all the parameters to the widget in the constructor in rc Lua. I'll post here when it's merged.
And I'll update the readme as well. Thanks for raising an issue.

**Comment by streetturtle** [comment]
I was wrong in the previous comment - translate widget is a bit different from other widgets, so my change to externalize the config of the widget in the rc.lua is not applicable here, so the best way to provide the api key is to paste it in secrets.lua
