### ISSUE TITLE
Batteryarc widget shows 0% whenever unplugged, acpi is correct.

### ISSUE THREAD

**Issue by vegtamr-ab** [streetturtle/awesome-wm-widgets#95]
So, when it's charging, all works correctly and widget shows current %, but when it's unplugged, the widget number is always 0, and even with high battery there is a notification with "low battery level"

**Comment by streetturtle** [comment]
Does it work as expected if you reload awesome?
Can you post the output of acpi please.

**Comment by vegtamr-ab** [comment]
No, reload doesnt work.
Battery 0: Discharging, 100%, rate information unavailable
Battery 0: design capacity 3952 mAh, last full capacity 3952 mAh = 100%
