### ISSUE TITLE
Trouble with widgets

### ISSUE THREAD

**Issue by nugget210** [streetturtle/awesome-wm-widgets#99]
I can't seem to get any of your widgets working at all on the three Awesome themes that I have (multicolor, powerline and powerline-blue).

Mainly I'm trying to use the spotify-widget.  I'm following your instructions but it says to put:

"local spotify_widget = require("awesome-wm-widgets.spotify-widget.spotify")" into rc.lua as well as the "spotify_widget()," 

But since these themes use theme.lua - do I put those lines in there instead as that's where the other widgets are being called.

I can't seem to get it to work when I put it in either.  I also have found a couple of sets of instructions for this - one with spotify_widget, and one with spotify_widget(), I can't seem to get either working.

Any suggestions?

**Comment by streetturtle** [comment]
Yes, it should be in theme.lua. Place 'require' at the top of the file, and widget itself in the "right widgets" section. It should be with parentheses. Please let me know if it works.

**Comment by nugget210** [comment]
Thanks very much for the quick reply.  

I thought I had tried every combination of in rc.lua and theme.lua and with/without the () but what you suggested fixed it up.  Cheers!
